# Generated by Django 3.2.13 on 2022-05-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('storyline', models.CharField(max_length=255)),
                ('cast', models.CharField(max_length=255)),
                ('registered_date', models.DateField()),
            ],
        ),
    ]
